version: "3.9"
services:
    rabbitmq3:
        container_name: Rabbitmq
        image: rabbitmq:management
        hostname: rabbitmqHost
        environment:
            - RABBITMQ_DEFAULT_USER=root
            - RABBITMQ_DEFAULT_PASS=admin1234
        ports:
            - "5672:5672"
            - "15672:15672"
        healthcheck:
            test: rabbitmq-diagnostics -q status
            interval: 1s
            timeout: 2s
            retries: 30
        networks:
            - myNetwork
    backgoundworker:
        container_name: Worker
        image: docker-lab.build.91app.io/arch/andylu/backgroundworker:latest
        hostname: worker
        depends_on:
            rabbitmq3:
                condition: service_healthy
        volumes:
        - type: bind
          source: ./BackgroundWorker/.env
          target: /app/.env
        networks: 
            - myNetwork
    dashboard:
        container_name: NMQ_dashboard
        image: docker-lab.build.91app.io/arch/andylu/dashboard:latest
        hostname: NMQ_dashboard
        ports:
            - "3001:3001"
        depends_on:
            rabbitmq3:
                condition: service_healthy
        volumes:
          - type: bind
            source: ./Dashboard/.env
            target: /app/.env
        networks:
            - myNetwork
networks:
    myNetwork: