version: "3.9"
services:
    rabbitmq3:
        container_name: rabbitmq
        image: rabbitmq:management
        hostname: rabbitmqHost
        environment:
            - RABBITMQ_DEFAULT_USER=root
            - RABBITMQ_DEFAULT_PASS=admin1234
        ports:
            - '5672:5672'
            - '15672:15672'
        healthcheck:
            test: rabbitmq-diagnostics -q status
            interval: 1s
            timeout: 2s
            retries: 30
        networks:
            - myNet
    backgoundworker:
        container_name: subscriber
        build: .
        hostname: subscriber
        depends_on:
            rabbitmq3:
                condition: service_healthy
        volumes:
        - type: bind
          source: ./.env
          target: /app/.env
        networks: 
            - myNet
networks:
    myNet: